urlshortner/short/urls.py
from django.urls import path,include
from . import views

app_name = "short"

urlpatterns = [
    
    path('',views.index,name = 'index'),
    path('signup/',views.signup,name = 'signup'),
    path('signin/',views.signin,name = 'signin'),
    path('logout/',views.user_logout,name = 'logout'),
    path('shorturl/',views.shorturl,name = 'shorturl'),
    path('<int:id>/detail/',views.detail,name = 'detail'),
    path('<str:shortcode>/',views.goto,name = 'redirect'),
    path('<int:id>/delete/',views.delete,name = 'delete'),
]

urlshortner/urlshortner/urls.py
from django.contrib import admin
from django.urls import path,include
from short import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('short.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT,)+staticfiles_urlpatterns()

urlshortner/short/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    full_name = models.CharField(max_length=30,null=False)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    mobile = models.IntegerField(null=False)
    def __str__(self):
        return self.user.username


class Bitly(models.Model):
    username = models.CharField(max_length=15,null=True)
    long_url = models.URLField(null=False)
    title = models.TextField(null=True)
    shortcode = models.CharField(max_length = 6,unique = True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    datewise = models.TextField()

    def __str__(self):
        return self.shortcode

urlshortner/short/forms.py
from django import forms
from .models import UserProfileInfo,Bitly
from django.contrib.auth.models import User
from . import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['email','password']


class UserProfileInfoForm(forms.ModelForm):
    con_password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = UserProfileInfo
        fields = ['full_name','mobile']

class Sign_in(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ['email','password']

class CreateSortCode(forms.ModelForm):
    class Meta:
        model = models.Bitly
        fields = ['long_url']

urlshortner/short/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from .forms import UserForm,UserProfileInfoForm,CreateSortCode
from .models import Bitly
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


def index(request):
    import json
    shortcodes = Bitly.objects.filter(username__iexact=request.user.username)[::-1]
    clicks = {}
    for x in shortcodes:
        instance = json.loads(x.datewise)
        clicks[x] = sum(instance.values())
    return render(request,'index.html',{'shortcodes':shortcodes,'clicks':clicks,'total_clicks':sum(clicks.values()),'len':len(shortcodes)})

def signup(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            if user_form.data['password']==profile_form.data['con_password']:
                print(profile_form.data['con_password'])
                user_name = user.email[:user.email.index('@')]
                user.username = user_name
                user.set_password(user.password)
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()

    return HttpResponseRedirect(reverse('short:index'))

def signin(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user_name = email[:email.index('@')]
        user = authenticate(username=user_name,password=password)
        if user:
            if user.is_active:
                login(request,user)
    return HttpResponseRedirect(reverse('short:index'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('short:index'))

def shorturl(request):
    from .utils import create_Sortcode,gettitle
    if request.method == 'POST':
        user_name = request.user.username
        form = CreateSortCode(data=request.POST)
        import json
        instance = form.save(commit=False)
        instance.shortcode = create_Sortcode()
        instance.datewise = json.dumps({})
        instance.username = user_name
        instance.title = gettitle(instance.long_url)
        instance.save()
    return HttpResponseRedirect(reverse('short:index'))

def detail(request,id):
    shortcode = Bitly.objects.filter(id__iexact=id)[::-1]
    return render(request,'page2.html',{'shortcode':shortcode[0]})


def goto(request,shortcode):
    import json
    import datetime
    qs = get_object_or_404(Bitly,shortcode__iexact = shortcode)
    if qs:
        today = datetime.datetime.now().date()
        instance = json.loads(qs.datewise)
        if str(today) in instance:
            instance[str(today)] += 1
        else:
            instance[str(today)] = 1
        qs.datewise = json.dumps(instance)
        qs.save()
    return HttpResponseRedirect(qs.long_url) 

def delete(request,id):
    if request.user.is_authenticated:
        qs = get_object_or_404(Bitly,id =id)
        if qs and request.user.username == qs.username:
            qs.delete()
    return HttpResponseRedirect(reverse('short:index'))

urlshortner/templates/index.html
<html>
    <head>
            <link rel="stylesheet" type="text/css" href="/static/urlshortner.css">
            <script src="/static/index.js"></script> 
    </head>
    <body id="body">
        <form method = "POST" action="{% url 'short:shorturl' %}">{% csrf_token %}
                <div id="sorturl">
                <div id="header"></div>
                <div id="content">
                    <div id="contentC1"></div>
                    <div id="contentC2">
                        <div id="logo_outer">
                            <div id="logoleft"></div>
                            <div id="logocenter"><img src="/media/Logo.png" style="height: 100%;width: 100%;"></img></div>
                            <div id="logoright"></div>
                        </div>
                        <div class="content2Rows"></div>                    
                        <div class="content2Rows" style="text-align: center;">Enter Long URL</div>
                        <div class="content2Rows" style="text-align: center;">
                            <input type="text" name=long_url placeholder="Long URL" style="position:relative;top:20%;width:90%;height: 100%;" required>
                        </div>
                        <div class="content2Rows"></div>  
                        <div class="content2Rows" style="text-align: center;">
                            <input id="button1" type="submit" value="Sort Me" style="position:relative;width:40%; top:30%;height:80%;">
                        </div>
                        <div class="content2Rows" style="text-align: center;">
                            <input id="button1" type="reset" value="Cancel" style="position:relative;width:40%; top:30%;height:80%;" onclick="closesorturl()">
                        </div>
                    </div>
                    <div id="contentC3"></div>
                </div>
                <div id="footer"></div>
            </div>
        </form>


        


        <form method = "POST" action="{% url 'short:signin' %}">{% csrf_token %}
            <div id="signin">
                <div id="header"></div>
                <div id="content">
                    <div id="contentC1"></div>
                    <div id="contentC2">
                        <div id="logo_outer">
                            <div id="logoleft"></div>
                            <div id="logocenter"><img src="/media/Logo.png" style="height: 100%;width: 100%;"></img></div>
                            <div id="logoright"></div>
                        </div>
                        <div class="content2Rows"></div>                    
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="Email"><span style="position:relative;top:30%;">Email Address</span></label></spam></div>
                            <div class="entries"><input type="email" name=email placeholder="Email Id" style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="password"><span style="position:relative;top:30%;">Password</span></label></spam></div>
                            <div class="entries"><input type="password" name=password placeholder="Password" style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows"></div>  
                        <div class="content2Rows">
                            <div class="label" ><input id="button1" type="submit" value="Submit" style="position:relative;width:40%; top:30%;height:60%;left: 8%;"></div>
                            <div class="entries">
                                <input id="button1" type="reset" value="Reset" style="position:relative;width:40%; top:30%;height:60%;left: -13%;">
                                <input id="button1" type="reset" value="Exit" style="position:relative;width:40%; top:30%;height:60%;left: 5%;" onclick="closesignin()">
                            </div>
                        </div>
                    </div>
                    <div id="contentC3"></div>
                </div>
                <div id="footer"></div>
            </div>
        </form>


        <form method = "POST" action="{% url 'short:signup' %}">{% csrf_token %}
            <div id="signup">
                <div id="header"></div>
                <div id="content">
                    <div id="contentC1"></div>
                    <div id="contentC2">
                        <div id="logo_outer">
                            <div id="logoleft"></div>
                            <div id="logocenter"><img src="/media/Logo.png" style="height: 100%;width: 100%;"></img></div>
                            <div id="logoright"></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="firstname"><span style="position:relative;top:30%;">Full Name</span></label></spam></div>
                            <div class="entries"><input type="text" name=full_name placeholder="Full Name" style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="Email"><span style="position:relative;top:30%;">Email Address</span></label></spam></div>
                            <div class="entries"><input type="email" name=email placeholder="Email Id" style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="mobile"><span style="position:relative;top:30%;">Mobile No.</span></label></spam></div>
                            <div class="entries"><input type="tel" name=mobile placeholder="Mobile No." style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="password"><span style="position:relative;top:30%;">Password</span></label></spam></div>
                            <div class="entries"><input type="password" name=password placeholder="Password" style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label"><spam class="label_property"><label for="conPassword"><span style="position:relative;top:30%;">Confirm Password</span></label></spam></div>
                            <div class="entries"><input type="password" name=con_password placeholder="Password" style="position:relative;top:20%;width:90%;height: 50%;" required></div>
                        </div>
                        <div class="content2Rows">
                            <div class="label" ><input id="button1" type="submit" value="Submit" style="position:relative;width:40%; top:30%;height:60%;left: 8%;"></div>
                            <div class="entries">
                                <input id="button1" type="reset" value="Reset" style="position:relative;width:40%; top:30%;height:60%;left: -13%;">
                                <input id="button1" type="reset" value="Exit" style="position:relative;width:40%; top:30%;height:60%;left: 5%;" onclick="closesignup()">
                            </div>
                        </div>
                    </div>
                    <div id="contentC3"></div>
                </div>
                <div id="footer"></div>
            </div>
        </form>


        <div id = "mySidenav" class="sidenav">
            <a href="" class="closebtn" onclick="closeNav()">&times;</a>
            {% if not request.user.is_authenticated %}
            <span onclick="opensignup()">New User</span>
            <span onclick="opensignin()">Sign In</span>
            {% endif %}
            {% if request.user.is_authenticated %}
            <a href="">Edit Profile</a>
            <a href="">Settings</a>
            <a href="{% url 'short:logout' %}">Logout</a>
            {% endif %}
        </div>
        <div id ="top">
            <div id ="topR1">
                <div id ="topR1logo"><img src="/media/Logo.png" style="width:100%;height:100%;"></div>
                <div id ="topR1tagname"><spam style="width:100%;height:100%;">AVIANJJAI</spam></div>
                <div id ="topR1search"><input id = "topR1searchinput" type="test" name="search" placeholder="Search"></div>
                <div id ="topR1create">
                    <div id="topR1createC1"><span style="position: relative;top:25%;" onclick="opensorturl()">CREATE</span></div>
                    <div class="dropdown">
                        <div class="dropdown-content">
                            <a onclick="opensorturl()">Short Link</a>
                            <a href="#">Campaign</a>
                        </div>
                    </div>
                </div>
                <div id ="topR1username"><span style="position: relative;top:25%;" >{{ request.user.username }}</span></div>
                <div id ="topR1menu"><img src="/media/menu.png" onclick="openNav()" style="width:100%;height:100%;"></div>
            </div>
        </div>
        <div id ="middle">
            <div id ="middleC1">
                <div id ="middleC1R1">
                    <div id ="middleC1R1Logo"><img src="/media/click.png" style="width:100%;height:100%;"></div>
                    <div id ="middleC1R1Content">
                        <div id ="middleC1R1ContentR1">{{ total_clicks }}</div>
                        <div id ="middleC1R1ContentR2">TOTAL CLICKS</div>
                        <div id ="middleC1R1ContentR3"></div>
                    </div>
                </div>
                <div id ="middleC1R2">
                    <div id ="middleC1R1Logo"><img src="/media/email.png" style="width:100%;height:100%;"></div>
                    <div id ="middleC1R1Content">
                        <div id ="middleC1R1ContentR1">1</div>
                        <div id ="middleC1R1ContentR2">Email,SMS,Direct</div>
                        <div id ="middleC1R1ContentR3">TOP REFERRER</div>
                    </div>
                </div>
                <div id ="middleC1R3">
                    <div id ="middleC1R1Logo"><img src="/media/location.png" style="width:100%;height:100%;"></div>
                    <div id ="middleC1R1Content">
                        <div id ="middleC1R1ContentR1">1</div>
                        <div id ="middleC1R1ContentR2">India</div>
                        <div id ="middleC1R1ContentR3">TOP LOCATION</div>
                    </div>
                </div>
            </div>
            <div id ="middleC2"></div>
        </div>
        <div id ="bottom">
            <div id ="bottomC1">
                <div id ="bottomC1R1">
                        <div class ="bottomC1R1C1"><span style="position: relative;top:25%;">{{ len }} Links</span></div>
                        <div class ="bottomC1R1C2"><span style="position: relative;top:25%;">Clicks</span></div>
                </div>
                <div class ="bottomC1content">
                    {% for shortcode in shortcodes %}
                        <div class ="bottomC1contentdate">
                            <div class ="bottomC1R1C1">{{ shortcode.created_date }}</div>
                        </div>
                        <div class ="bottomC1contenttitle">
                            <div class ="bottomC1R1C1"><a href="{% url 'short:detail' shortcode.id %}" target = "abc" style = "text-decoration: none;color:  #464c50;">{{ shortcode.title|slice:":40" }} .....</a></div>
                        </div>
                        <div class ="bottomC1contentlink">
                            <div class ="bottomC1contentlinkC1">
                                <a href="{% url 'short:redirect' shortcode.shortcode %}" style = "text-decoration: none;color: #ee6123;position: relative;top:25%;">{{ request.get_host }}/{{ shortcode.shortcode }}</a>
                            </div>
                            <div class ="bottomC1contentlinkC2"><span style="position: relative;top:25%;">{{ clicks|get_item:shortcode }} Clicks</span></div>
                        </div>
                        <div id ="line"></div>
                    {% endfor %}
                </div>
                
            </div>
            <div id ="bottomC2">
                <iframe name ="abc"></iframe>
            </div>
        </div>
    </body>
</html>

urlshortner/templates/page2.html
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/static/page2.css">
        <script src="/static/index.js"></script>
    </head>
    <body>
        <div id="detail">
            <div id="detailcontentdate"><span style="position:relative;top:20%;">CREATED {{ shortcode.created_date }} | {{ request.user.username }}</span></div>
            <div id="detailcontenttitle"><span style="position:relative;top:15%;">{{ shortcode.title }}</span></div>
            <div id="detailcontentlongurl"><span style="position:relative;top:20%;">{{ shortcode.long_url }}</span></div>
            <div id="detailcontentshorturl">
                <div id="detailcontentshorturlname"><span style="position:relative;top:20%;">{{ request.get_host }}/{{ shortcode.shortcode }}</span></div>
                <a href=""><div class="detailcontentshorturlbutton"><span style="position:relative;top:20%;" onclick ="copy('{{ request.get_host }}/{{ shortcode.shortcode }}')">COPY</span></div></a>
                <a href=""><div class="detailcontentshorturlbutton"><span style="position:relative;top:20%;">SHARE</span></div></a>
                <a href="{% url 'short:delete' shortcode.id %}" target="_top"><div class="detailcontentshorturlbutton"><span style="position:relative;top:20%;">DELETE</span></div></a>
            </div>
            <div id ="line"></div>
        </div>
    </body>
</html>